### ISSUE TITLE
Automatic Mode Setting Is Not Saved (and Thus Doesn’t Work) 

### ISSUE THREAD

**Issue by rue** [stoically/temporary-containers#110]
- Temporary Containers Version: 0.8.1
- Firefox Version: 59.0.2
- Operating System + Version: OS X 10.13.2
- Non-default Options/Preferences in Temporary Containers:
- Other installed Add-ons + Version: MAC 6.0.0

### Actual behavior

Automatic Mode setting is not saved despite no error. Opening new tabs w/ cmd+t opens them in the default container. Opt+C does open in a new temporary, as does cmd-clicking links.

### Expected behavior

Automatic Mode is saved, and new tabs (cmd+t) are opened in a new temporary container.

### Steps to reproduce
1. about:addons
2. TC -> Preferences -> General
3. Check Automatic Mode: checkbox is checked)
4. Click Save: green Preferences Saved appears
5. Close tab
6a. Cmd+T to open new tab: tab is opened in default container
6b. Opt+C to open new tab: tab is opened in new temporary container
6c. Cmd-click link: tab is opened in new temporary container
6d. Open MAC-assigned domain in any way: tab is opened in assigned container
7. Navigate back to preferences
8. Automatic Mode is unchecked

### Notes

"[onMessage] message received" {"method":"savePreferences","payload":{"preferences":{"automaticMode":true,...}
"[onMessage] saving preferences"
"[persist] storage persisted"

And yet we get 

"[maybeReloadInTempContainer] automatic mode not active and not a moz page, we ignore that"

**Comment by stoically** [comment]
Now, this is interesting. Thanks for the relevant part of the debug log, because that shows `automaticMode: true` is transmitted - however, since the refactoring in #91 `automaticMode` is now an object - so for some odd reason your preferences moz-extension:// page seems to load an old version of the `shared.js`. Could you try force reloading the preferences tab without cache (not sure what's the keycombo on MacOS for that) and see if it'll then work?

**Comment by rue** [comment]
Completely removing and reinstalling seemed to work (force refresh, restart, disable did not).

The code in moz-extension://589435ae-3afc-9a40-b5da-bc2a8d840d34/ui/shared.js was setting `automaticMode.active`, and yet the actual execution sent the `automaticMode: true` variant. Seems like a bug in webextension handling somewhere, then?

**Comment by stoically** [comment]
Dang, should've asked for a copy of the storage so I could've had a chance to debug this. Without its unfortunately just speculating on my end. What maybe - and probably - happened is that the migration from version <0.80 wasn't successful and you ended up with a corrupt storage - but in this case you should've noticed a complete reset of your preferences and it should've shown you a "Error loading preferences" on the preferences page. But since you wanted to enabled Automatic Mode again - did it just stopped working for you?

**Comment by stoically** [comment]
Was able to reproduce the behavior you described. This indeed happened because the migration from <0.80 didn't get executed for you. Unfortunately this is most likely a problem with Firefox where `runtime.onInstalled` isn't fired or fired before the Add-on had the time to register its event handler. I'll look into:

- [ ] Executing <0.80 Migration if automaticMode is a boolean to at least make sure users don't end up with the corrupt state described here
- [ ] Trying to reproduce `runtime.onInstalled` not correctly getting fired and filing a Bugzilla Report

Also going to change how Migration works, opened new Issue for that: #112

**Comment by stoically** [comment]
A workaround is to execute migration manually (in case someone hits the same problem and ends up here before I get the fix out):

*Note: Only do this if you updated to version 0.81, not after that! (you can check the current version under "Add-ons" and click "More Info" next to "Temporary Containers")*

- Open a new tab and navigate to "about:debugging"
- Tick the "Enable debugging" checkbox
- Scroll down to Temporary Containers and click the "Debug" link
- Confirm the dialog with OK, you now see "Developer Tools" with "Console" selected
- Type into the console `tmp.migration.onUpdate({previousVersion: '0.77'});`
- Close Developer Tools
- Untick "Enable debugging" again
- Close preferences tab and open it again (if still open)

Should now work as expected.

**Comment by rue** [comment]
Excellent, thank you! Glad you were able to find the root cause too, I was in too much of a hurry to get productive to debug much further :)

**Comment by stoically** [comment]
Tracking progress for the needed change in #112
