### ISSUE TITLE
SIMPLE QUESTION/HELP

### ISSUE THREAD

**Issue by Decopi** [stoically/temporary-containers#113]
Hi,

First, thanks a lot for Temporary-Containers... what an excellent add-on!

I have a RSS reader feeds add-on (FEEDBRO), with more than 200 RSS generating lots of cookies and webgarbage.
In normal browsing, every time I want to open FEEDBRO in a Temporary Container, a message popups saying: "FEEDBRO is not working in private browsing mode".

Please, a simple question/help: Is there a way to use FEEDBRO with Temporary-Containers?

Thanks a lot!

[https://addons.mozilla.org/en-US/firefox/addon/feedbroreader/](url)

**Comment by stoically** [comment]
Hey, thanks for the kind words. Unfortunately there's nothing I can do about that. You'd have to ask the developers of Feedbro whether they can implement support for Containers in General. If you try to open the moz-extension:// page in a Permanent Container (e.g. by long-clicking the New Tab Icon an selecting "Person"), the same message will appear.

They probably check if the current tab as a different `cookieStoreId` than `firefox-default` and if so show the message. A possible fix would be to check for `firefox-private` instead, or to allow `cookieStoreId`s starting with `firefox-container-`.

Hope they'll help you out.

**Comment by Decopi** [comment]
@stoically thanks for the prompt answer!

I checked both, the normal Firefox container, and Private Browsing, and sadly FEEDBRO shows the same message. You're right, it is not a workaround with Temporary-Containers. It a FEEDBRO issue, not ready to work with containers.

I tried to contact the FEEBRO dev this morning, but not answer yet. That's why I decided to contact you.

Thank you anyway, and again... congratulations for so nice add-on!

**Comment by Decopi** [comment]
Hi, @stoically , please just one last question:

The only need I have with containers, is to be able by default to open all my webpages always in temporary containers. And always to delete everything after "x" minutes I closed a tab. I don't care about the other million options/alternatives. And I can do that with your add-on.

According to my ignorance, I can't do that in Firefox trough "about:config" (with preferences / without add-ons).
Neither I can't do that with FirefoxMulti-AccountContainers add-on. It requires manually to add one by one each website in containers. And containers are not deleted after tab closing.

Am I right?
Or there is another simpler way to do what I need, without add-ons?
Or perhaps there is another better/simpler add-on for my needs?

Thanks in advance for your help!

**Comment by stoically** [comment]
As far as I know there's no way to get the same functionality without an Add-on and I'm also not aware of an Add-on with a similar feature-set.

**Comment by Decopi** [comment]
Hi @stoically ... may I have one more last question? lol :-)

In the main page of your add-on ("About this extension"), you wrote a very useful text explaining lot of stuff. And you compared other privacy methods with your add-on.

My question is about the "Disabled third-party cookies, maybe even with First Party Isolation" case. Let's take the same case, but with Containers:
If I have a shopping site in a Container, with cookies and everything else inside its Container (1st and 3rd-parties)... then, any user activity will be tracked by the shopping site inside this Container. Am I right? So, if inside this Container a link is visited, the shopping cookie will track it. Containers don't avoid tracking inside same Container... right?
I can't see clearly the difference between Containers and your example ("Disabled third-party cookies, maybe even with First Party Isolation").

A Mozilla' employee recently explained to me that FPI (First Party Isolation) is a kind of hardened Container. Normal Containers put 1st and 3rd-parties together in same Container (isolated from other Containers). But FPI puts 1st-party in a Container (isolated even from its own 3rd-parties).
So, if I well understood this Mozilla' guy, FPI is strongest than normal Container.

This Mozilla' employee also added: At FPI, 1st-party is isolated from 3rd-parties, and might break webpages. That's the reason Containers was created, to keep 1st and 3rd-parties together in same Container, but isolated from other Containers. And that's the reason why Mozilla recommends Containers and not FPI.

I asked this Mozilla' employee if the use of FPI eliminates the need for Containers. And his answer was "yes"... in terms of privacy, there is no need for Containers if users have FPI enabled. He said that Containers are useful only when 1st-party needs 3rd-parties.

Now and back to your "Disabled third-party cookies, maybe even with First Party Isolation" case... here I am a little confuse. Please, can you explain me the difference between your add-on and FPI, and why your add-on is better than FPI?

Thank you again in advance, and my apologizes for taking your time and attention.

**Comment by stoically** [comment]
FPI and Containers use the same "Origin Attributes separation" under the hood, so you effectively get a "Container" for the domain currently loaded in the Tab, that's correct. The main differences to the actual Firefox Container feature (contextualIdentities) are:

* If you load the same domain in two different Tabs with FPI activated, then those two tabs share the same underlying data (cookies, cache storage) - with separate Containers they don't
* If you navigate inside the same Container to a "New Domain" that embeds/uses content from "Other Domains" you visited in the same Container, then its possible for the "Other Domains" to access their data if they're embedded as 3rd party on the "New Domain" - with FPI they can't access their data. This also makes it so that FPI breaks some Websites if they rely on cookies being present when redirecting, like sometimes with SingleSignOn / OAuth logins (so in this case the "1st party needs the 3rd-party"). 

For me personally I feel like it enhances privacy if I can visit the same site in multiple tabs without them easily being able to correlate the visits by using (super)cookies or storage (that they still are able to correlate them in theory is another story). Think: Multiple tabs for search-engine queries, visits on social-media/coding or even news sites, etc

Besides that you get the additional features Temporary Containers offers like:
* All first- and third-party data is removed together with a container. You can't achieve the same currently with FPI in default containers by means of Add-ons. The only way is to wipe the *complete* browsing data
* Automatically open new Tabs if it's an external link - thanks to the Isolation feature
* And sometimes the "Delete History" feature also comes in handy

Also, it's entirely possible to use both at the same time - however, I didn't test that myself, yet. But I feel like I should write an article on the matter anyway, hehe.

**Comment by Decopi** [comment]
@stoically thank you for such good answer.

One final conclusion is that FPI and ContainerTab are subjects where Mozilla have not good texts explaining functions, differences etc. It is not even clear (at least for me) how both work together etc. You are right, an article will be welcome, but Mozilla should be responsible for that. After Facebook scandal past week, Mozilla took advantage offering Containers. But as usual, Mozilla explained nothing, not even a word about FPI.
I tried to read stuff on the web, but honestly, you were my best info source. Your explanations are very clear. Thank you.

And a second final conclusion is that your add-on is spectacular!
Not FPI, neither Mozilla Multi Containers etc are opening tabs in separate containers by default. Also, are not deleting the garbage after using containers. You add-on do that and more! So useful!

Thank you again for everything!

**Comment by Decopi** [comment]
Hi @stoically ,

I introduced your "Temporary-Containers" as a must add-on, at https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.1-Extensions

Here is my post at the end of the webpage:

https://github.com/ghacksuserjs/ghacks-user.js/issues/294
