### ISSUE TITLE
Dragging and dropping urls onto a window

### ISSUE THREAD

**Issue by Zlewness** [stoically/temporary-containers#117]
OS: Windows 7

Is there a way to force a new container when I do this? As an example open two Firefox windows, then test dragging urls from the url bar on one onto the tab bar or url bar on the other, the url is opened in the same container even in automatic mode.

**Comment by stoically** [comment]
You don't actually need two Windows, this is also reproducible in just one Window. Unfortunately I can't fix this since there's (afaik) no way to detect that specific action. From the code's point of view it just looks like you opened a tab in the same Temporary Container and started loading an URL in it (e.g. Middle Mouse or Ctrl+Left Mouse clicking looks the same for the code).

The only way to handle this is on a `Per Domain Isolation` basis. If you configure a Domain to `Always open in new Temporary Containers` there then it'll reopen in a new Temporary Container in this case. Hope that helps.

**Comment by fefo-dev** [comment]
Is this limitation still true? Was filling an issue but there's no reason to if nothing changed.

Thanks.
