### ISSUE TITLE
Whitelist accounts.firefox.com

### ISSUE THREAD

**Issue by maxnordlund** [stoically/temporary-containers#132]
### Notes
Like https://accounts.firefox.com/settings I think https://accounts.firefox.com/ should be whitelisted to always open in the default container. Doesn't make much sense it open it in another one IMO.

See mozilla/multi-account-containers#1194, which also includes about:addon output.

**Comment by stoically** [comment]
Is there a reason to not just assign accounts.firefox.com to a Permanent Container using MAC and use that Permanent Container for it instead of the Default Container? Since logging into and using Firefox Accounts also works with Temporary Containers I personally don't see the need to add that specific Domain to the "Exclude from Automatic Mode / Isolation"-List. Or do I miss something here and something does indeed not work?

I might consider to make the Exclude-List also available in the preferences while implementing #104 so one could configure custom Domains (alongside with AMO and getpocket).

**Comment by maxnordlund** [comment]
It's about logging in to addons.mozilla.org which when I turned off temporary containers worked seamlessly. But I couldn't decontain using https://gitlab.com/mjanetmars/switch-container, it just switched to a new temporary container. I get why that happens, and I don't really consider it a bug as it comes from the interaction between this and MarsCats extension.

It also comes from the Firefox sync feature. It works for me, but I enabled it before automatic mode. Go to about:preferences?entrypoint=menupanel#sync and click the "Manage account" link, it goes to accounts.firefox.com.

If it would be possible to edit in the future that's really awesome, but I do think it should be on the whitelist shipped with temporary containers.

**Comment by listalltabs** [comment]
Just for information, accounts.firefox.com is amongst a list of firefox/mozilla domains attached to the new v60 pref **extensions.webextensions.restrictedDomains**. This appears to stop the listed domains from being isolated from or assigned to a container. (Actually, you can assign them to a container, via MAC, but the assignment isn't honoured).

**Comment by stoically** [comment]
@listalltabs Interesting, just tested and it seems that all domains in `extensions.webextensions.restrictedDomains` are not able to be seen or canceled by `webrequest.onBeforeRequest` - and with that can't get reopened into a container; though they still can get loaded in a container if the container is opened first. But with that upcoming change from Firefox, I guess we can close this Issue since it will automatically behave like OP requested with Firefox v60+
