### ISSUE TITLE
Google Container Issue

### ISSUE THREAD

**Issue by briant97** [stoically/temporary-containers#135]
It looks like there may be a conflict with the Google Containers plugin.  The facebook one seems to work fine.  However with Google containers it doesn't open it as expected.

- Temporary Containers Version:
- Firefox Version:
- Operating System + Version:
- Non-default Options/Preferences in Temporary Containers:
- Other installed Add-ons + Version:

### Actual behavior
..

### Expected behavior
..

### Steps to reproduce

1. ..
2. ..
3. ..

### Notes
..

**Comment by stoically** [comment]
If you have a problem specifically with the Google Container Add-on, then you might want to head over to http://github.com/containers-everywhere/contain-google and open an Issue there. You might also want to provide What you expect to happen, what actually happens and Steps to Reproduce or otherwise it could be hard to help you.
