### ISSUE TITLE
"Ignoring requests to" doesn't work anymore

### ISSUE THREAD

**Issue by Perflyst** [stoically/temporary-containers#149]
- Temporary Containers Version: 0.90
- Firefox Version: 60.0.1
- Operating System + Version: Ubuntu 16.04 (4.15.0-22)

### Actual behavior
Whether you check both checkboxes or additionally adjust the about:config rule, addons.mozilla.org and getpocket.com will always open in a no-container.

### Expected behavior
If you check the checkboxes, both should be contained into a (new) temporary container (with automatic mode).

### Steps to reproduce
1. Enable automatic mode
2. Check the checkboxes
3. Navigate to addons.mozilla.org

### Debug log
[debug.txt](https://github.com/stoically/temporary-containers/files/2035373/debug.txt)

**Comment by stoically** [comment]
Ticking the checkboxes means that the requests to that Domain will get ignored from Temporary Containers, added a Note to the preferences clarifying that.

Also, like pointed out here https://github.com/stoically/temporary-containers/issues/132#issuecomment-387781416 starting with Firefox Version ~0,61b4 there's a new about:config key that needs additional configuration.

However, getpocket works for me by just unticking the checkbox and then navigating to "https://getpocket.com" (http version gets not contained).

Closing this for now since I believe it works as expected, thanks for the report tho!
