### ISSUE TITLE
How to isolate YouTube and other Google services while logged in

### ISSUE THREAD

**Issue by AdKiller** [stoically/temporary-containers#156]
I am trying to achieve the following and would appreciate any advice on how to do it correctly.

**Aim:** permanently isolate the following using Mozilla multi-account-containers:
- Youtube (logged in)
- Gmail (logged in)and Docs (logged in), and Calendar (logged in) 
- Google Search (not logged in) and other Google services (not logged in).
using temporary-containers
- I also want the convenient of automatic temporary-containers for every other site.
- Also force open Google search results in a new tmp container

**Problem:**

- I can't login to Youtube or GMail because when I try to login accounts.google.com takes me out of permanent container to a tmp container and loging fails.
- I can't figure out how to always open Google search results in a new tmp container.

**Comment by curiosity-seeker** [comment]
I can't answer all of your questions as I do not use Google services for privacy reasons. However, in order to open Google search results in a new tmp container you can try the following:
1. In the TC settings go to _Isolation -> Per domain_ and add
`/^https:\/\/www\.google\.com\/search/`
to the _Domain Pattern_ field.
2. Select _Enabled_ in the _Always open in new Temporary Containers field_.

For your other problems you might want to try to add the respective domains to the _Always open in new Temporary Containers_ field and select _Disabled_.

You will find more info [here](https://github.com/stoically/temporary-containers/wiki/Per-Domain-Isolation).

**Comment by yssmcl** [comment]
An alternative could be [Google Container](https://addons.mozilla.org/en-US/firefox/addon/google-container/).

**Comment by stoically** [comment]
> * I can't figure out how to always open Google search results in a new tmp container.

You can use the Per Domain Isolation with the RegExp mentioned by @curiosity-seeker to achieve that behavior.

> * I can't login to Youtube or GMail because when I try to login accounts.google.com takes me out of permanent container to a tmp container and loging fails.

Like mentioned by @GingerPlusPlus this is solved by adding the domain to Always Open In your Google-Container with Multi-Account Containers.
