### ISSUE TITLE
Can't figure out how to "always allow" a particular domain

### ISSUE THREAD

**Issue by echosa** [stoically/temporary-containers#168]
Using Multi-Account Containers, I have containers set up for various sites, including Amazon, GOG, and other sites where I buy stuff. On most of these sites, I use PayPal to pay. However, I find that I always have to go to the Temporary Containers settings, then go to `Isolation -> Multi-Account Containers`, disable that setting, make the purchase, then re-enable that setting.

That's a pain to do everytime, so I'm trying to figure out how to make it so that PayPal is allowed everywhere, even with that setting on. I tried setting up exclusions and other settings in `Isolation -> Per Domain`, but nothing I've done has worked. Instead of PayPal opening in whatever tab/container I'm currently in, it always opens into a temp container unless I disable `Isolation -> Multi-Account Containers`.

How do I set up Temporary Containers to allow PayPal (or any other website) to be loaded from anywhere regardless of MAC permanent container setup or Temporary Container setup?

**Comment by xarx00** [comment]
I guess that you could add a pattern to TC Settings > Isolation > Exclude Target/Link Domains.
But havent't tested that. If you succeed, please leave a note.

**Comment by echosa** [comment]
I tried that already. Either I configured it wrong, or It isn't working.

**Comment by xarx00** [comment]
I have just tried that. Two remarks:

1. Anyway, you're right, it doesn't work.
2. Verify that your exclusion stays in the config. Because it's adding is very counter-intuitive. First you have to create a general pattern in the top input field. And at second you have to create an exception for that pattern! Then save it (on another tab).

I've got set:
General > Automatic Mode = off
Isolation > Multi-account container = Enabled
In Isolation > Per Domain > Domain I have tried one-by-one (and other configs too):

a. pattern = "*.somedomain.com", Always=disabled, PermanentAllowed = false, Excluded="www.somedomain.com"
b. pattern = "*", Always=disabled, PermanentAllowed = false, Excluded="www.somedomain.com"
c. pattern = www.somedomain.com, Always=disabled, PermanentAllowed = true, Excluded none

and tested on https://www.somedomain.com.

**Comment by xarx00** [comment]
May be also related to #159.

**Comment by stoically** [comment]
@echosa This could be solved by #152 which would allow to add Domain Patterns which are always ignored by TC. Closing this in favor of the mentioned issue. A workaround would be to add the paypal domain(s) to [Containerise](https://addons.mozilla.org/firefox/addon/containerise/) as "No Container" - though you'd have to use version 2.4.0 until https://github.com/kintesh/containerise/pull/49 gets merged and published or you will run into problems.

@xarx00 You're right, configuring the excluded domains was a quick hack, I'm hoping to get that fixed with #104. I'm going to update the wiki to explain the exclude feature better too, what it does is: If you have the Per Domain pattern `*.example.com` and Exclude `www.example.com` you have to navigate from `bar.example.com` to `www.example.com` and in this case it'll stay in the same Temporary Container. It will not work if you navigate from `bar.anotherexample.com` to `www.example.com`.
