### ISSUE TITLE
Edit default container list

### ISSUE THREAD

**Issue by colans** [stoically/temporary-containers#200]
By default, the container list is:

- Personal
- Work
- Banking
- Shopping

I'd rather have something like:

- Anonymous (not logged in)
- Client A
- Client B

...for Web development.

How can one edit the list?  I can't find anything in the configuration.

**Comment by colans** [comment]
> Firefox Multi-Account Containers was first introduced as "Containers" available only in Firefox Nightly. It went on to be a Test Pilot Experiment, where we improved the user experience and added new features. Now it exists here as an extension that can be installed by all Firefox users.
> 
> Although you can still use the feature built into Firefox Nightly, we recommend using this extension [Firefox Multi-Account Containers] as it has a richer user experience.

@SoloRaven  So it looks like I can disable this one, and just use that?  Why it is recommended to use the two together?

**Comment by colans** [comment]
Maybe if you want temporary and permanent containers?  In any case, thanks!

**Comment by crssi** [comment]
Your first post question has nothing to do with TC.

In Firefox, goto Options -> General -> Tabs
Click on "Settings..." button... from here on I assume you will know what to do.

Cheers

**Comment by colans** [comment]
Interesting.  So it looks like this stuff is in core FF now.  If that's the case, why are either of these add-ons still necessary?

**Comment by SoloRaven** [comment]
Hi colans,

The way I understand all of this is that the built int container features within Firefox is more geared towards the creation of permanent” or longer term containers which you might want to use over and over to group certain sites into for example your bank and PayPal stuff could always open up in a Banking container and your Facebook and Twitter stuff could be placed into some sort of “Social Media” container with the added benefit that you will remain logged in on those sites (if you so choose).

It just makes compartmentalizing sites very easy and of course there is all the privacy benefits as well because what happens in your Vegas container stays in your Vegas container (could not help myself LOL).

Temporary Containers on the other hand, the way I use it, creates a new temporary container for each and every site that is NOT allocated to a permanent container.  So when I search Google, the results could be in container 1 and when I click on one of the results it opens in container 2 and so on…these containers obviously inherit all the privacy benefits from their more permanent cousins so there is all of that PLUS the way I have mine set up is that once a close a tab which is in a temp container, that container self-destructs and all its contents is deleted which makes maintenance for unimportant sites a breeze.
So, you could go with just a few semi-permanent containers if that suffices or you could get the full monty and also use Temp Container plugin to apply the same benefits but only to disposable containers.

The “Multi-Account Container” plugin on the other hand was meant to make managing your semi-permanent containers easier as it provides a nice little icon shortcut like the one I demonstrated in my screenshots.  

"Temp Container" plugin deals with the temporary ones that will be removed once you close the tabs.

Hope this helps a bit!

**Comment by crssi** [comment]
As @SoloRaven explained but shorter.
If you browse within container then some active content cannot access what its in a different contaner and vice versa. Also when a temporary container is destroyed, so are cookies and all those hidden super cookies you were not aware that exists.
TC is one of the best addons for Firefox.
https://github.com/ghacksuserjs/ghacks-user.js/issues/492#issuecomment-450579318
How to make FF more secure, least traceable: https://github.com/crssi/Firefox
And the best resource for firefox preferences and tightening: https://github.com/ghacksuserjs/ghacks-user.js

Cheers

**Comment by colans** [comment]
Thanks for the great explanations!
