### ISSUE TITLE
Load multiple bookmarks (same domain) in one container

### ISSUE THREAD

**Issue by bodisor** [stoically/temporary-containers#220]
Opening multiple (same domain) **bookmarks** at once via 'ctrl+left click' (or menu>open all) loads them in multiple containers instead of a single one.
If the folder contains more than 2-3 links (6+), TC manages to open some of them in same container (number and color). For example, out of 10 bookmarks it manages to open one or two containers with two links in it/them. But this behavior is random, since sometimes none open in same container.

I've read issue #105, but mine is different. Also, the color and number being wrongly reported is not an issue for me, since MAC reports those links in different containers as well.

Normal **page** navigation (ctrl+click) works as expected: new links (single domain) open in same container, reported so by both TC (color and number) and MAC. MAC also loads them as expected, in one container (once associated with one).

- TC(0.91) in automatic mode
- Isolation > Global - **all** set to 'navigation target domain does not match the active tabs domain (sub-domains won't get isolated)'
- Isolation > Per Domain nets the same result
- Also tested on a clean (otherwise empty) profile (FF v65)

**Comment by stoically** [comment]
The expected behavior when opening multiple links from bookmarks in Automatic Mode is that every URL opens in a new TC. That's because every bookmark URL is opened in a new tab and Automatic Mode is meant to reopen URLs into new TCs in this case.

The Isolation only takes effect if you navigate or mouse click in an already fully loaded website. In this case, if navigation/mouseclick happens, TC can compare the target against the already loaded URL in a tab - that's not possible when a new tab is opened for a bookmark.

> TC manages to open some of them in same container 

This indeed sounds like #105 - do you use the "Reuse available numbers" preference?

**Comment by bodisor** [comment]
I see.. I wanted to get rid of MAC and use TC only. I'll stick with both for now, since MAC manages bookmarks as expected.

As for some links opening with matching number & color, it **was** with 'reuse available numbers'. With 'keep counting' they were always different.

Close this, since you gave a clear answer and I have no other issues.
Thank you.

**Comment by stoically** [comment]
> I wanted to get rid of MAC and use TC only. I'll stick with both for now, since MAC manages bookmarks as expected.

I guess you have the bookmark URL configured to "Always open in" a specific permanent container with MAC. In this case it's the expected behavior from MAC that all URLs open in the same permanent container. That's why MAC and TC complement each other - one for permanent container management, one for temporary containers.

> As for some links opening with matching number & color, it was with 'reuse available numbers'. With 'keep counting' they were always different.

Thanks for letting me know.
