### ISSUE TITLE
Force Gmail to logout on browser close

### ISSUE THREAD

**Issue by snowbound** [stoically/temporary-containers#221]
What I would really prefer to be able to do in Firefox is to AUTOMATICALLY log me out of multiple Gmail accounts when Firefox is closed. Right now I have to manually set a Google HSID cookie to session only every time I open up the previous session's tabs via Tab Session Manager extension.  The problem is that Google long ago removed the ability to create a current session only cookies for logins and instead keeps you logged in unless you actually remember to use their logout option under their pulldown menu.

I spent countless hours searching for an extension to allow this. Firefox own Multi-account container extension does not help since it keeps one logged in.  I can't delete cookies for google,com in Firefox like one can do in Chrome since in FF it also deletes my 2FA cookie which I want to keep between sessions as well as my YouTube preferences cookie.

**Comment by stoically** [comment]
[Forget Me Not](https://addons.mozilla.org/firefox/addon/forget_me_not/) added cookie specific expressions in its latest update. Click the `?` in its popup and check `Cookie specific expressions`. You can set it to remove the cookie on browser startup. It's not possible for Add-ons to do something when the browser closes since there are no APIs for it available.
