### ISSUE TITLE
Feature request/doc issue: Have the ability to exclude certain URLs from MAC containers

### ISSUE THREAD

**Issue by maxnordlund** [stoically/temporary-containers#231]
- Temporary Containers Version: 0.91
- Firefox Version: 66.0.1
- Operating System + Version: Mac OS X 10.14.3
- Non-default Options/Preferences in Temporary Containers:
- Other installed Add-ons + Version: MAC and Switch Container

### Actual behavior
I can't seem to figure out how to isolate just a part of a web site. I'm trying to make it so that I'm logged in to YouTube, and can thus view my feed, while still watch videos inside temporary containers.

### Expected behavior
To be able to force some URLs to be in temporary containers, even though the main domain is assigned to a MAC one.

### Steps to reproduce

I tried fiddling around with the per domain isolation rules, using `/^https?:\/\/(www.)?youtube\.com\/watch/` but couldn't get it to work

### Notes
This might be more of an issue with the documentation if it's already possible to do, otherwise it would be sweet if it could be done :)

---

Thanks for this addon, it really has transformed the way I surf the web ❤️

**Comment by stoically** [comment]
If you assigned a domain using MAC, you can no longer overwrite that domain using TC isolation rules (since MAC is not aware of TC). Though, if you didn't check "Remember my choice" for the "Always open in" assigned domain, isolation rules will still apply and let you choose between a TC and the MAC assigned domain (as long as the originating request didn't came from a permanent container: #225).

A workaround might be to give [Containerise](https://addons.mozilla.org/firefox/addon/containerise/) a try - they added RegExp support in the latest update. With that you could have a rule like `@^https?//(www\.)?youtube\.com/?$` specified in Containerise for your youtube container (and make sure you don't have conflicting rules with MAC, or you'll get endlessly spawning tabs) - everything not matching that rule can get handled by TC.

Hope that helps - and glad you like the Add-on. <3

**Comment by maxnordlund** [comment]
Aha, that explains it. Yeah I figured it wasn't going to be that easy, and I'll definitely give Containerise a try. Thanks
