### ISSUE TITLE
Re open tabs in container after Firefox crash

### ISSUE THREAD

**Issue by rominail** [stoically/temporary-containers#263]
When firefox crash (ie:power interruption) and you re open firefox, depending on firefox personnal settings, it asks to restore opened tabs when firefox crashed
If containers were opened, firefox re open the link but without the container (neither all the belonging cookies/sessions)
I don't know if I'm clear
This feature might be handy if possible

**Comment by stoically** [comment]
TC removes containers on startup that no longer have open tabs. It might be possible to check whether an `about:sessionrestore` tab is open, and in that case delay the removing the containers.

**Comment by rominail** [comment]
Good
Do i close the issue?

**Comment by stoically** [comment]
Since that's something that could be implemented at some point (hence the enhancement label), it would make sense to leave the issue open.

**Comment by stoically** [comment]
With just published version 0.102 TC will now no longer remove containers as long as a `about:sessionrestore` tab is open.

**Comment by stoically** [comment]
Starting with version 1.6 the check for `about:sessionrestore` tabs will only run once on the first container cleanup when the browser starts. The checks after that will not take `about:sessionrestore` tabs into account, like the first interval after 1 minute. That's to prevent not cleaning up containers because there's a `about:sessionrestore` tab open *somewhere*. If you run into problems with that or feel like one minute is not enough, please let me know.
