### ISSUE TITLE
Tab strip blinks and jumps on new tabs even with "replace the Current Tab" option

### ISSUE THREAD

**Issue by deepsweet** [stoically/temporary-containers#290]
- Temporary Containers Version: 1.1
- Firefox Version: 69.0b3
- Non-default Options/Preferences in Temporary Containers: "Instead of creating a new tab replace the Current Tab"
- Other installed Add-ons + Version: Containerise v3.2.0

### Actual behavior
Every new opened tab _very noticeable_ "blinks" and tab strip "jumps": by creating a new tab (another one) and closing an empty "old" one. It's difficult to explain :)

### Expected behavior
It reuses the newly opened tab.

### Steps to reproduce

1. open an empty or navigate to a new tab

### Notes
Maybe it's like that by design or technical limitation, I just found the actual behavour described above very annoying.

**Comment by stoically** [comment]
To reopen a tab, created by Firefox in the default container, in a new temporary container tab it is necessary to create an entirely new tab and close the old tab, since the Firefox API doesn't allow to move tabs between containers. So there's unfortunately nothing I can do about that.

The "Replace tabs" preference is just about closing the old tab in case Isolation takes place (there's always a new tab opened by default to retain history of the old tab, which is otherwise lost).

Regarding Automatic Mode itself (affecting new tabs), you could set the Advanced Automatic Mode preference to "Don't instantly reopen", that prevents the initial flickering when opening new tabs. Hope that helps.

**Comment by deepsweet** [comment]
I see, thanks for the explanation. Just in case someone else find this issue – [discourse.mozilla.org: Feature Request: A way to change the container of the current tab](https://discourse.mozilla.org/t/feature-request-a-way-to-change-the-container-of-the-current-tab/18931/7)

**Comment by stoically** [comment]
My pleasure. Here's the related issue over at MAC: https://github.com/mozilla/multi-account-containers/issues/1029
