### ISSUE TITLE
Installed but not working, grayed out?

### ISSUE THREAD

**Issue by 3d73a4a412** [stoically/temporary-containers#298]
I installed  Temporary Containers and it shows up in the address bar menu and in the tabs bar it is grayed out and I cant click on it. I have set it to automatic mode and nothing either. I have tried a myriad of settings but nothing?

I didnt see an issue that looked like this so thought I'd ask/post.

below is a pix to give an idea of the issue:

![TemporaryContainers_result](https://user-images.githubusercontent.com/25825755/62542706-5a9ebb00-b82a-11e9-9192-ccca215a3c76.gif)

**Comment by stoically** [comment]
TC is disabled in private windows since containers unfortunately aren't available in private browsing. If you have `Never remember history` in the Firefox options active, then you're in "Permanent private mode", which you'd have to disable in order to use TC. See also https://github.com/mozilla/multi-account-containers/issues/469.

**Comment by 3d73a4a412** [comment]
doh! THANK YOU! I didnt realize that. Sorry for such a noob question.

**Comment by stoically** [comment]
No worries. TC should probably at least give a hint in the preferences if opened in private browsing, since it isn't obvious at all why it doesn't work.

**Comment by crssi** [comment]
@3d73a4a412 
You can also disable history, without entering "Permanent private mode":
``` js
user_pref("places.history.enabled", false);
```
Cheers 😉
