### ISSUE TITLE
Address bar icon should show red icon when isolation is disabled

### ISSUE THREAD

**Issue by Arthaey** [stoically/temporary-containers#299]
It would be nice if the icon in the address bar showed the same red exclamation point as the tab bar icon, when isolation is disabled.

Reason: I use the TreeStyleTab extension for my tabs instead of the usual tab bar, so the built-in tab bar is hidden for me most of the time. I've been surprised a couple times that I had accidentally left isolation disabled for longer than I meant to, because I didn't have an obvious visual reminder.

**Comment by stoically** [comment]
Can't you move the TC icon from the navbar into the toolbar (right-click, customize)?

**Comment by Arthaey** [comment]
That's a good workaround for now, thanks!

But I like to keep as few toolbar icons as possible; if I can take advantage of the in-address icon instead, that would be perfect.

That said, I'd agree that this is a low-priority feature request. :)

**Comment by stoically** [comment]
Glad it helps :)

Do you mean the actual container icon/text? Because that can't be changed. Or the popup icon in the addressbar ([pageAction](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/pageAction))? The problem with the pageAction is that it doesn't support native badges like the toolbar does - so I'd have to manually create icons for it.

**Comment by Arthaey** [comment]
I mean the popup icon in the address bar.

I didn't realize that it had different support for badges; that's a bummer. I agree that this makes my request much lower priority. ;)
