### ISSUE TITLE
Use storage.sync API to sync preferences across computers

### ISSUE THREAD

**Issue by Natim** [stoically/temporary-containers#30]
Today I switched computer and Temporary Containers was automatically installed in the new computer (thanks to Sync) but I was a bit puzzle to see that my preferences (Automatic Mode off) was not taken into account.

**Comment by Natim** [comment]
Following a discussion about privacy it would make sense to add an opt-in preferences to enable synchronization preferences across devices. uBlock Origin is an example of that feature.

**Comment by stoically** [comment]
When opting into storage.sync with the preference the decision has to be made how to handle the initial sync
1. Overwrite local preferences if there's something in storage.sync at the time of opting-in
2. Overwrite preferences that are already in storage.sync with current local preferences

Since it's entirely possible that Firefox Sync isn't connected (or not yet activated in Firefox) when opting-in, I see no reliable way of making sure that `2` will work because in case of conflict the Server always wins - [if Firefox Sync got implemented like chrome](https://wiki.mozilla.org/WebExtensions/chrome.storage.sync#What_Chrome_does) (couldn't find other info on that).

So I'd say `1` is the way to go - with a warning to the user that his local preferences might get overwritten.

**Comment by glasserc** [comment]
The current implementation uses "client wins" on synchronization of everything except for crypto keys. Of course, "server wins" and "client wins" are kind of misnomers, because all changes originate from clients. "Server wins" is really more like "first-to-server wins", and "client wins" is more like "last-to-server wins". Anyhow, we use the second of these.

All of the above solutions eventually require losing one device's set of preferences in favor of the others. Maybe it's possible to do slightly better and merge the synced data with the data stored locally. For instance, you might use a variant of B where you only migrate from storage.local to storage.sync once per device, probably by storing a flag in storage.local saying "I've already been migrated".

To mitigate the concern of race conditions with preference changes being made on two devices separately, I'd recommend only using storage.sync (as you suggest). If you have a preferences panel where you've generated HTML based on preferences, you can add a listener to storage.onChanged to update the HTML when new preferences come in.

**Comment by stoically** [comment]
> Anyhow, we use the second of these.

Good to know, thanks for the explanation!

> All of the above solutions eventually require losing one device's set of preferences in favor of the others. Maybe it's possible to do slightly better and merge the synced data with the data stored locally.

Yeah, I guess that's why e.g. uBlock really just provides a separate "Import / Export Interface" with enabled cloud-syncing. Nothing happens automatically.

Loosing preferences without you knowing why is like the worst UX that possible can happen. So I'm personally also in favour of only providing an additional interface to "Import / Export" preferences to avoid that under any circumstance. That requires more work, of course, but I feel like it's the right thing to do.

> you can add a listener to storage.onChanged

Ah, didn't know about this one, that could come in handy for that case, yeah.

**Comment by stoically** [comment]
Closing, since making this a *good implementation* would require a fair amount of work, for imho not enough value in return. A workaround is using the Export/Import introduced in #86. I'd be open for a PR though, if someone wants to tackle it.

**Comment by stoically** [comment]
Starting with [v1.0beta7](https://github.com/stoically/temporary-containers/releases/tag/v1.0beta7) it's possible to export/import to/from Firefox Sync.
