### ISSUE TITLE
Automatic mode - new tab opens 2 tabs and close one immediatly

### ISSUE THREAD

**Issue by marquito23** [stoically/temporary-containers#301]
- FF v. 67
- If automatic mode is selected, new tab button (+) opens 2 tabs.  One gets closed shortly within 1 second immediatly and the other one remains correctly.

Opening/ closing the second tab is annoying.

**Comment by stoically** [comment]
Thanks for taking the time to open the issue.

That's unfortunately how automatic mode is supposed to work - it needs to reopen the new tab in a temporary container and close the old tab in the default container, since there's no way for Add-ons to override in which container new tabs are opened. Most of the time the reopening is fast enough that it's mostly not noticeable, but some users experience longer reopenings which are indeed not good UX.

You could configure automatic mode under `Advanced` to `Don't instantly reopen`, which makes it so that the reopening happens on first navigation, not when opening a new tab. Hope that helps - let me know if it doesn't.

**Comment by marquito23** [comment]
I don't understand that last part,
> You could configure automatic mode under Advanced to Don't instantly reopen
under advanced is no option for configure "Don't instantly reopen". It is only written, like a comment:
Automatic Mode
Instantly reopen new tabs in Temporary Containers. You might lose the first few already typed characters in the address bar when reopening takes too long, but it prevents new tabs from writing and reading cookies in the default container (default).

What do you mean with "that the reopening happens on first navigation, not when opening a new tab" - what is first navigation?

Addon version 1.2

**Comment by stoically** [comment]
>  It is only written, like a comment

It's a dropdown with two possible options - you can click on it and select the `Don't instantly reopen` one.

> what is first navigation?

The first navigation happens when you open a website in a new tab, like when searching with the address bar or opening a specific website address.

**Comment by marquito23** [comment]
> It's a dropdown with two possible options - you can click on it and select the Don't instantly reopen one.

Yes, there is dropdown but without options - I have the screenshot of advanced tab attached.

![190825145043_2](https://user-images.githubusercontent.com/54498626/63650155-df089d80-c747-11e9-9895-6a5360e006c2.jpg)

**Comment by stoically** [comment]
You can click on the `Don't instantly reopen` sentence, which activates the option.

**Comment by marquito23** [comment]
Oh, I found it - I had not recogniced as selectable option. It works fine, thank you for your patience.
