### ISSUE TITLE
npm install: semantic-ui failed to install gulp

### ISSUE THREAD

**Issue by mdhooge** [stoically/temporary-containers#313]
- Temporary Containers Version: 9189c01ad8431dad42663d0e5579ebee4c3fc246
- Operating System + Version: ArchLinux
- Node.js: v12.12.0
- npm: 6.11.3

I'm trying to build the add-on but the `npm install` command fails with message:

```
> semantic-ui@2.4.2 install /home/michel/dev_3rd/temporary-containers/node_modules/semantic-ui
> gulp install

fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/home/michel/dev_3rd/temporary-containers/node_modules/natives/index.js:143:24)

```

This seems to be a known problem between node and gulp… Can you please detail the versions you're using?

Thanks
Michel

**Comment by mdhooge** [comment]
The requirements in Readme.AMO.md state Ubuntu 18.04 AND latest NodeJS… So I tried something a bit older with NVM: the LTS/dubnium version (v10.16.3) and I managed to produce the addon.
So maybe this isn't *your* configuration, but at least that works ;-)

**Comment by stoically** [comment]
Oh, interesting, thanks for the hint. I think I actually only tested with node 10, so latest node is indeed not correctly documented. Problem here is that gulp is a devdependency of semantic-ui, and since semantic-ui seems abandoned (last commit oct 2018), chances are [the issue](https://github.com/Semantic-Org/Semantic-UI/issues/6818) gets never fixed and I have to remove semantic-ui as dependency from TC, which isn't exactly a problem since I use copies of the libs in the vendor directory anyway and have the dependency just for version tracking.
