### ISSUE TITLE
Temporary Containers not deleted when Private Window is open

### ISSUE THREAD

**Issue by cdrcnm** [stoically/temporary-containers#319]
- Temporary Containers Version: 1.3
- Firefox Version: 71.0b5 (Developer Edition) 
- Operating System + Version: Arch Linux
- Non-default Options/Preferences in Temporary Containers: Delete no longer needed Temporary Containers 5 minutes after

### Actual behavior
The no longer temporary container are never deleted, even after a Firefox restart.
I wiped the local storage and the problem is still there, and changed the default timeout from 15 to 5 minutes and immediately after the last tab close didn't change anything.

### Expected behavior
The no longer temporary container are  deleted after 5 minutes.

Debug log, with the "delete no longer needed Temporary Containers" set at "After the last tab close"
[debug log](https://github.com/stoically/temporary-containers/files/3808097/temporarycontainer-debug.txt)

**Comment by stoically** [comment]
Thanks for the log, it seems like that you probably still have an `about:sessionrestore` tab open somewhere. I'll look into modifying the check introduced in #263 to timeout after some minutes, so in case a restore tab is still open, it'll remove containers anyway at some point.

**Comment by stoically** [comment]
If you happen to find the restore tab and close, you can force a full cleanup either by restarting Firefox or with `tmp.container.cleanup(true)` on the debug console.

**Comment by cdrcnm** [comment]
I'm pretty sure I didn't have a restore tab opened, and I closed and opened Firefox a few times.
But I had a few pinned tabs, who are automatically launched at start. After closing every tab and restarting Firefox the TempContainer are properly deleted. So, one of the pinned tab had a problem, or Firefox was stuck in a weird state.
Thanks.

**Comment by stoically** [comment]
Interesting. So yeah,

> Firefox was stuck in a weird state

is probably the most likely scenario in that case, because the check that prevented the cleanup (the one that prints "canceling" in the log), is [pretty simple](https://github.com/stoically/temporary-containers/blob/f96e53e7068ada05600e43be7a16b8c0e348730b/src/background/tabs.js#L258-L276) and mostly relies on `browser.tabs.query` API to return the correct result.

I'll try to play around with pinned tabs in the Firefox beta and see if I can force the issue somehow.

Glad you found a solution tho.

**Comment by stoically** [comment]
Oh, I just realized, the "pretty simple check" is pretty wrong since I introduced #263. Before that [it did the right thing](https://github.com/stoically/temporary-containers/blob/203cc6eacbb062155b1b4033ca4cdcaf79a318cd/src/background/tabs.js#L196) and didn't do a cleanup when only incognito tabs are open, because you might close the "normal" window(s) with "session restore" active, while keeping an incognito window open, and in that case it'd cleanup the containers even though they shouldn't because of session restore - now it prevents container cleanup always if there's an incognito tab open. Did you by chance have an incognito tab/window open?

**Comment by cdrcnm** [comment]
Yes I have an incognito window open.
I did a few more test. Every container closed when I have a incognito window open aren't cleaned.

**Comment by stoically** [comment]
Ah! That explains it. I'll push out the fix with the next update - thanks for confirming.

**Comment by stoically** [comment]
Fixed in [v1.4beta2](https://github.com/stoically/temporary-containers/releases). Please let me know if something doesn't work as expected.
