### ISSUE TITLE
TC creates permanent containers in Firefox Multi-Account Containers

### ISSUE THREAD

**Issue by scmm-stack** [stoically/temporary-containers#328]
- Temporary Containers Version: 1.3
- Firefox Version: 70.0.1 (64-bit)
- Operating System + Version: Windows 10 1909
- Non-default Options/Preferences in Temporary Containers:
- Other installed Add-ons + Version:
Amazon.com	1.1	true	amazondotcom@search.mozilla.org
AudioContext Fingerprint Defender	0.1.3	true	{ab0ae774-f22f-479b-9b1b-6aff11bf6f5c}
base64 decoder	1.0	true	{b20e4f00-ab03-4a88-90e7-4f6b6232c5a9}
Bing	1.0	true	bing@search.mozilla.org
Canvas Fingerprint Defender	0.1.5	true	{94249bf3-29a3-4bb5-aa30-013883e8f2f4}
Change Timezone (Time Shift)	0.1.4	true	{acf99872-d701-4863-adc2-cdda1163aa34}
Checkmarks	1.3.0	true	{bd97f89b-17ba-4539-9fec-06852d07f917}
Clear Cache	3.2	true	clearcache@michel.de.almeida
DuckDuckGo	1.0	true	ddg@search.mozilla.org
eBay	1.0	true	ebay@search.mozilla.org
Firefox Multi-Account Containers	6.1.1	true	@testpilot-containers
Font Fingerprint Defender	0.1.0	true	{96ef5869-e3ba-4d21-b86e-21b163096400}
Google	1.0	true	google@search.mozilla.org
Grammar and Spell Checker - LanguageTool	2.4.2	true	languagetool-webextension@languagetool.org
LastPass: Free Password Manager	4.37.0.1	true	support@lastpass.com
Mute sites by default	1.10	true	@mute-sites-by-default
Nano Defender	15.0.0.170	true	{fcf60470-b210-4c17-969e-9ae01491071e}
Nimbus Screen Capture: Screenshots, Annotate	15.4.5	true	nimbusscreencaptureff@everhelper.me
Temporary Containers	1.3	true	{c607c8df-14a7-4f28-894f-29e8722976af}
Twitter	1.0	true	twitter@search.mozilla.org
uBlock Origin	1.24.0	true	uBlock0@raymondhill.net
User-Agent Switcher and Manager	0.3.4	true	{a6c4a591-f1b2-4f03-b3ff-767e5bedf4e7}
WebGL Fingerprint Defender	0.1.2	true	{2cf5dbed-78fe-4bd5-9524-38fdf837be98}
Wikipedia (en)	1.0	true	wikipedia@search.mozilla.org
Print Edit WE	24.4	false	printedit-we@DW-dev

### Actual behavior
When you use Temporary Containers in Automatic Mode it opens URL in temp containers as expected but it also creates permanent containers in Firefox Multi-Account Containers. After an hour of browsing I have over 300 unwanted permanent containers.

### Expected behavior
Do not create permanent containers in Firefox Multi-Account Containers.

### Steps to reproduce

1. Install Temporary Containers and set Automatic Mode
2. Install Firefox Multi-Account Containers
3. Open a new tab

### Notes
The debug section in the bug template needs an update.

**Comment by stoically** [comment]
From Firefox's point of view all containers are permanent containers. They're just temporary in the sense that they're deleted after usage. Hence why you see them in MAC as well. To not show them in MAC they would need to ask the [TC API](https://github.com/stoically/temporary-containers/wiki/API).

If containers aren't removed as expected, even though there are no tabs open for containers and the default 15minutes are over, that might be because there's a Private Window open (see #319). That's fixed in [v1.4beta2](https://github.com/stoically/temporary-containers/releases). 

Thanks for the debug log hint, I'll update the issue template to point to the [wiki](https://github.com/stoically/temporary-containers/wiki/Debug-Log) instead.

Hope that helps.
