### ISSUE TITLE
.xpi permission problem

### ISSUE THREAD

**Issue by rampaa** [stoically/temporary-containers#330]
- Temporary Containers Version: 1.4beta2
- Firefox Version: 69.0.3 (64-bit)

### Actual behavior
When I try to install .xpi from any website that isn't addons.mozilla.org, I get a message that says "Firefox prevented this site from asking you to install software on your computer" and can't install the add-on. 

### Expected behavior
Depending on the case, I should either get an confirmation pop up that says "Allow `domain address
` to install an add-on?" (Case 1) or when I refresh the link, it should ask me "Add `Extension?`" (Case 2)

### Steps to reproduce
Case 1:
1. Make sure automatic mode is on and Isolation>Global>Navigation is set to "Different from Tab Domain"
2. Go to https://github.com/stoically/temporary-containers/releases/tag/v1.4beta2 and click on temporary_containers-1.4beta2-an+fx.xpi

Case 2:
1. Make sure automatic mode is on and Isolation>Global>Navigation is set to "Different from Tab Domain"
2. Go to http://127.0.0.1:24613/captcha/recaptchav2/mexa.sh/?id=1574899876929 and click "Firefox Extension Download"

**Comment by stoically** [comment]
That's a Firefox limitation (maybe a bug) and should be asked about on the Firefox channels (like [Bugzilla](https://bugzilla.mozilla.org/)). What happens is that TC cancels the original xpi request due to isolation (different domain) and opens the xpi download in a new temporary container tab - and it seems like Firefox doesn't like to ask about Add-on installation if the request isn't initiated by an explicit user interaction (like entering something in to the address bar or clicking a link), so nothing TC can change/fix.

The workaround here is to focus the address bar in the new tab and click enter, which then proceeds to ask about the add-on installation.

Hope that helps.

**Comment by rampaa** [comment]
Thanks for the tips. I am aware that it's mostly Firefox limitation but Firefox is not exactly responsive in regards to such requests. So I thought asking here first. 

I would like to be able to exclude URLs from being isolated with a pattern like `*.xpi` if possible but I am not sure how feasible of a solution this would be.

**Comment by stoically** [comment]
Happy to help. Adding the regexp `/\.xpi$/` as global target domain exclusion pattern would achieve that for URLs ending with `.xpi`, yes. However, the GitHub downloads redirect to something where the .xpi is part of the query parameter, so the URL doesn't end with `.xpi` anymore. In that case something like `/(\.xpi$|\?.*\.xpi\&)/` would work. It works and its probably unlikely it would lead to false positives, but it *could* lead to false positives. (Beware leading/trailing whitespaces when adding regexp patterns, I'll refactor that so it ignores such whitespaces)
