### ISSUE TITLE
temporary container breaks passbolt

### ISSUE THREAD

**Issue by enko** [stoically/temporary-containers#365]
I'm using [passbolt](https://www.passbolt.com/) a password manager which has an extension which provides the crypto primitives at work. When I try to login it somehow fails and the login fails and I'm back at the login screen. When I disable Temporary Containers I can login without a problem.

When I look at the debug log of temporary containers I see these entries:

```
Unchecked lastError value: Error: Script 'moz-extension://ac25599d-f8e8-45b7-97dd-27125bf5ffce/data/vendors/dom-testing-library-event.js' result is non-structured-clonable data index.min.js:13060
    createScriptCallback moz-extension://ac25599d-f8e8-45b7-97dd-27125bf5ffce/index.min.js:13060
Unchecked lastError value: Error: Script 'moz-extension://ac25599d-f8e8-45b7-97dd-27125bf5ffce/data/tpl/login.js' result is non-structured-clonable data 2 index.min.js:13060
    createScriptCallback moz-extension://ac25599d-f8e8-45b7-97dd-27125bf5ffce/index.min.js:13060
Unchecked lastError value: Error: Script 'moz-extension://ac25599d-f8e8-45b7-97dd-27125bf5ffce/data/js/lib/port.js' result is non-structured-clonable data 2 index.min.js:13060
    createScriptCallback moz-extension://ac25599d-f8e8-45b7-97dd-27125bf5ffce/index.min.js:13060
Unchecked lastError value: Error: Script 'moz-extension://ac25599d-f8e8-45b7-97dd-27125bf5ffce/data/js/quickaccess/quickaccess.js' result is non-structured-clonable data index.min.js:13060
    createScriptCallback moz-extension://ac25599d-f8e8-45b7-97dd-27125bf5ffce/index.min.js:13060
```

`ac25599d-f8e8-45b7-97dd-27125bf5ffce` is the ID of the [passbolt extension](https://addons.mozilla.org/de/firefox/addon/passbolt/).

I'm running Firefox Nightly 74.0a1 (2020-01-27) (64-Bit) and temporary containers 1.7.

**Comment by stoically** [comment]
Does the temporary container number change when trying to login? (from say tmp1 to tmp2) If it doesn't then it might be a problem with containers in general (happens) - could check by opening a permanent container (e.g. by long-clicking the new tab button and opening any of the permanent containers) and trying to login.

The errors are unrelated to TC - unfortunately, the debug inspect also shows errors from other Add-ons (sometimes); not sure why since it's confusing.

**Comment by stoically** [comment]
Ah, I just realized it's about another Add-on not working correctly, not a website. TC doesn't influence other Add-ons at all, since Add-ons in general can't access other `moz-extension` pages. So this is most likely a problem with the passbolt extension not working properly when the container feature in Firefox is active. You could check by disabling TC and installing/enabling any other container Add-on, like e.g. [MAC](https://addons.mozilla.org/firefox/addon/multi-account-containers/) and then try to login.

**Comment by enko** [comment]
Sorry I should have been more clear:

Passbolt is a website, but uses an extension to support itself. I have the website inside a permanent "work" container. But I tinkered a bit arround and if I disable tc and let it inside the work container it still wont let me login. I think thats more a problem of the passbolt extension/website. I'll fill a bug there.

But that leaves me with another problem. I'm also using your other extension Switch Container Plus and if I decontain the tab, it is instantly moved to a temporay container. If I add the domain to exclude target domain in the tab bar menu, it does not change anything. Maybe I'm missing something?

Thanks for your time and effort!

**Comment by stoically** [comment]
No worries. Filing a bug over at passbolt is the way to go then.

> If I add the domain to exclude target domain in the tab bar menu, it does not change anything

That's the automatic mode kicking in, not isolation. Unfortunately no easy way to exclude domains from that currently. Easiest way would probably be to open a "No container tab" using the keyboard shortcut which can be activated in the advanced preferences.

**Comment by enko** [comment]
And there is a already a bug report: https://github.com/passbolt/passbolt_browser_extension/issues/41
