### ISSUE TITLE
[Feature Request] open a new container in current tab or close the previous tab when left-clicking links, but open link in new container tab if middle mouse button is used.

### ISSUE THREAD

**Issue by RoguedBear** [stoically/temporary-containers#506]
The title is not pretty clear but I'll try my best to explain:
If I was not using temporary containers and i would normal click on links it would open in the current tab. If i would click the link using middle mouse button link would open in a new tab.

So a workaround or an option in the settings to open new links in a container tab but closing the previous tab when using left click, but opening the link in a new tab without closing the previous one with middle mouse click.

Having this behavior makes tab management easy

**Comment by crssi** [comment]
I am using left click to always stay in the same container, since it solves also a breakages with logins over 3rd party pages.
There is an exception where search site (DDG for example) always opens like middle click.

So... middle click always opens in new tab... and always open in a new container when target domain is different than a source.
It woks for me for "years" now.

The configuration I am using its not a secret, you can find it in my github/firefox profile.
I hope it will help you somehow.

Cheers

**Comment by RoguedBear** [comment]
@crssi 
I had a look your settings and imported them and while going through the settings what all was different i found this setting which also does the job for left click:

![image](https://user-images.githubusercontent.com/39442192/118934309-dae2d180-b967-11eb-8e6f-b52ce5902e88.png)

so now middle click works (your settings!), and left click also closes the previous tab (this setting). If i have to go back a page i need to `ctrl+shift+t` then but its fine.

So i guess it does it for this issue then 😄 

Thanks for your help!

**Comment by crssi** [comment]
Happy to be helpful 😄 

Cheers
