### ISSUE TITLE
0.63 Occasionally Opens Multiple Tabs for the Same Link

### ISSUE THREAD

**Issue by rue** [stoically/temporary-containers#66]
Noticed this happening today, and probably not coincidentally latest TC update was today.

- Temporary Containers Version: 0.63
- Firefox Version: 58.0.2 
- Operating System + Version: OS X 10.13.2
- Non-default Options/Preferences in Temporary Containers: Mouse Clicks -> Ctrl/Cmd+Left Mouse -> only if not in same domain (maybe others, will add)
- Other installed Add-ons + Version: Multi-Account Containers 5.0.1

### Actual behavior
Upon Cmd-clicking a link from Firefox _or_ Mail.app, sometimes (not always) Firefox keeps opening multiple tabs for the link. Trying to close these tabs opens more of them until presumably some total number are open, at which point the tabs can be closed.

I’ll try to add a repro later when I have time (and unless this is enough info for you to figure out what might be going wrong).

### Expected behavior
A single tab is opened with the correct page.

### Steps to reproduce
TBA

### Notes
TBA

**Comment by stoically** [comment]
Hi, I'm guessing the link you're opening is assigned using Multi-Account Containers? In that case, this can happen because since version 0.58 TC needs MAC version 6.0.0. If it's not an assigned link, further information would be greatly appreciated.

However, TC shouldn't go completely bonkers with MAC version 6.0.0 if the link is assigned, I'm gonna add a safety measure.

**Comment by go2null** [comment]
Figured out the same as stated by @stoically - only happens if domain is assigned a regular container with MAC.

MAC [6.0.0](https://github.com/mozilla/multi-account-containers/releases/tag/6.0.0) is available on [Mozilla Add-ons](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/); so I manually upgraded.

Issue not observed since.

**Comment by rue** [comment]
Same repro, and problem’s gone with MAC. Thanks!

**Comment by go2null** [comment]
confirmed fixed: on one of my machines, had <6.0.0 MAC and issues occured; upgraded MAC to 6.0.0 and no problem with same link as before.
