### ISSUE TITLE
Preserve openerid when switching to temporary container

### ISSUE THREAD

**Issue by kilotaras** [stoically/temporary-containers#73]
- Temporary Containers Version: 0.64
- Firefox Version: 58.0.2
- Operating System + Version: tested on OS X and Windows 
- Non-default Options/Preferences in Temporary Containers: open by Ctrl/Cmd+Click -> Always
- Other installed Add-ons + Version: TreeStyleTab 2.4.16, MAC 6.0.0

### Actual behavior
![image](https://user-images.githubusercontent.com/590292/36944161-1100f96a-1f9f-11e8-8888-d47fc0e95002.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/590292/36944162-1a8fe64e-1f9f-11e8-8e18-0e74a9774c06.png)

### Steps to reproduce

1. Go to any site
2. Cmd/Ctrl+Click on any link

### Notes

MAC had the same issue but fixed it in latest release https://github.com/mozilla/multi-account-containers/pull/1066

**Comment by stoically** [comment]
Just published version 0.65 with the change, thanks for the report and PR. Let me know if something doesn't work as expected.

**Comment by stoically** [comment]
Had to disable version 0.65 because a issue popped up in #69 where it's no longer possible to save preferences. I've published version [0.66beta1 on the beta channel](https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/versions/beta) with the change, which you could test there. Also, if you could check whether you have problems with preferences loading/saving (especially adding Website pattern to "Always per Website") and let me know if so, that'd be awesome.

**Comment by kilotaras** [comment]
@stoically save works, preserved through browser restart

**Comment by stoically** [comment]
Thanks for the quick check. That's reassuring.

**Comment by stoically** [comment]
Turns out it was a misbehaving Firefox/NoScript, all good, version 0.66 is shipped. Thanks again.
