### ISSUE TITLE
Disable it for a new blank tab

### ISSUE THREAD

**Issue by rgamici** [stoically/temporary-containers#94]
- Temporary Containers Version: 0.73
- Firefox Version: 61
- Operating System + Version: Debian
- Non-default Options/Preferences in Temporary Containers: Automatic mode on
- Other installed Add-ons + Version: Multi-Account Containers 6.0

### Actual behavior
When I open a new tab using ctrl + T, or by clicking on the default new tab button, it takes some time (around one second) to assign the temporary container (in a newer tab, and close the other one).
When I press C-t and immediately start typing the website address (or whatever), the information I typed is lost when a new tab is opened with the new container.
Ex.: C-t "github" -> new tab with "hub" on the address bar.
[debugMain.txt](https://github.com/stoically/temporary-containers/files/1813949/debugMain.txt)

### Expected behavior
Do not create a new temporary container for the blank page.

### Steps to reproduce

1. ..
2. ..
3. ..

### Notes
Another problem related to the blank page is that as it does not have an address, it is not considered different from the target link.
Even with the option "Ctrl/Cmd+Left Mouse" set to "\[If the domain is different]", the tabs opened from the blank page get the same temporary container.
[debug_linkfromblankpage.txt](https://github.com/stoically/temporary-containers/files/1813950/debug_linkfromblankpage.txt)

**Comment by stoically** [comment]
Hi, this got already implemented in #36 and is available under "Advanced > Automatic Mode" - it even was the default for a while, but got changed back [because of reasons](https://github.com/stoically/temporary-containers/issues/36#issuecomment-367404363). Regarding Mouse Clicks on about: pages - those can't get catched because WebExtensions can't inject contentscripts into about: pages and that'd be needed for Mouse Clicks detection to work. But that would be covered with the "Don't reopen" Automatic Mode too.

However, what I realized because of this is, that with the "Reopen" Automatic Mode, you might carry around cookies set from about:newtab in that new Temporary Container - and that's not good. I'll have to look into how to avoid that, but I guess the only way around is to always open a new Temporary Container if the Navigation originates from an about:newtab (in Automatic Mode).

**Comment by stoically** [comment]
I've opened #96 to track the mentioned cookie problem. The "Don't reopen" advanced preference should solve your problem, though. Let me know if not.

**Comment by rgamici** [comment]
Thanks for your reply.

It solved my problem.
But I fell that it is a little confusing to configure it for the first time, there are too many options separated in several tabs.

**Comment by stoically** [comment]
> It solved my problem.

Glad it worked.

> But I fell that it is a little confusing to configure it for the first time, there are too many options separated in several tabs.

Not separating into tabs wouldn't make it better. And if there are a lot of configurations available then I don't expect people to get everything right off the bat. That's why that specific preference is under "Advanced". However, if you have concrete suggestions on how to better structure the preferences, I'd be happy to hear it. I'm already planning to merge Always per Website/Isolation/Mouse Clicks into one tab #91
